# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/cyd293/ccatalog/models/category/fields.yaml

# Model Class name
modelClass: Cyd293\CCatalog\Models\Category

# Default redirect location
defaultRedirect: cyd293/ccatalog/categories

# Create page
create:
    title: Create Category
    redirect: cyd293/ccatalog/categories/update/:category_id
    redirectClose: cyd293/ccatalog/categories

# Update page
update:
    title: Edit Category
    redirect: cyd293/ccatalog/categories
    redirectClose: cyd293/ccatalog/categories

# Preview page
preview:
    title: Preview Category
