# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Brand

# Model Form Field configuration
form: $/cyd293/ccatalog/models/brand/fields.yaml

# Model Class name
modelClass: Cyd293\CCatalog\Models\Brand

# Default redirect location
defaultRedirect: cyd293/ccatalog/brands

# Create page
create:
    title: Create Brand
    redirect: cyd293/ccatalog/brands/update/:brand_id
    redirectClose: cyd293/ccatalog/brands

# Update page
update:
    title: Edit Brand
    redirect: cyd293/ccatalog/brands
    redirectClose: cyd293/ccatalog/brands

# Preview page
preview:
    title: Preview Brand
