# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Index

# Model Form Field configuration
form: $/cyd293/ccatalog/models/index/fields.yaml

# Model Class name
modelClass: Cyd293\CCatalog\Models\Index

# Default redirect location
defaultRedirect: cyd293/ccatalog/index

# Create page
create:
    title: Create Index
    redirect: cyd293/ccatalog/index/update/:id
    redirectClose: cyd293/ccatalog/index

# Update page
update:
    title: Edit Index
    redirect: cyd293/ccatalog/index
    redirectClose: cyd293/ccatalog/index

# Preview page
preview:
    title: Preview Index
